services:
  nginx:
    build: 
      context: .
      dockerfile: public/Docker/Dockerfile
    container_name: nginx
    ports:
      - "8082:80"
    volumes: 
      - .:/var/www/html/todo
      - ./public/Docker/todo.conf:/etc/nginx/conf.d/todo.conf
    depends_on:
      - app
    networks:
     - todo-network  
    
  app:
    build: 
      context: .
      dockerfile: public/php/Dockerfile
    container_name: php
    volumes:
      - .:/var/www/html/todo
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge  
