---
- name: Start docker compose
  command: docker-compose -f /var/www/todoapp/docker-compose.yml up -d
  args:
    chdir: /var/www/todoapp/

- name: Reload nginx
  service:
    name: nginx
    state: reloaded   

- name: Ensure docker containers are running
  command: docker ps -a

# - name: wait for DB to be ready
#   wait_for:
#     port: 3306
#     delay: 10
#     timeout: 60
      
- name: restart container of app
  command: docker-compose -f /var/www/todoapp/docker-compose.yml up -d app